apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync
spec:
  project: default
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/yanghoon/argo-apps.git'
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
