apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-kafka
  namespace: argo
spec:
  project: default
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://yanghoon.github.io/charts'
    targetRevision: 0.1.0
    chart: argo-app-kafka
