apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-kafka-2
  namespace: argo
spec:
  project: default
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://yanghoon.github.io/charts'
    targetRevision: 0.1.*
    chart: argo-app-kafka
    helm:
      values: |-
        global:
          namespace: kafka-2
        apps:
          kafka:
            parameters:
              service.nodePort: 30094
      # parameters:
      # - name: global.namespace
      #   value: kafka-2
      # - name: apps.kafka.parameters.service\.nodePort
      #   value: "30093"
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false